# Spatial Joins Exercises

Here\'s a reminder of some of the functions we have seen. Hint: they
should be useful for the exercises!

-   `sum(expression)`: aggregate to
    return a sum for a set of records
-   `count(expression)`: aggregate to
    return the size of a set of records
-   `ST_Area(geometry)` returns the
    area of the polygons
-   `ST_AsText(geometry)` returns WKT `text`
-   `ST_Contains(geometry A, geometry B)` returns the true if geometry A contains geometry B
-   `ST_Distance(geometry A, geometry B)` returns the minimum distance between geometry A and
    geometry B
-   `ST_DWithin(geometry A, geometry B, radius)` returns the true if geometry A is radius distance or less from geometry B
-   `ST_GeomFromText(text)` returns `geometry`
-   `ST_Intersects(geometry A, geometry B)` returns the true if geometry A intersects geometry B
-   `ST_Length(linestring)` returns the length of the linestring
-   `ST_Touches(geometry A, geometry B)` returns the true if the boundary of geometry A touches geometry B
-   `ST_Within(geometry A, geometry B)` returns the true if geometry A is within geometry B


Uncomment and run the following cell to install the required packages.

In [2]:
%pip install duckdb leafmap lonboard
import duckdb
import leafmap

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.4.4)
Requirement already satisfied: leafmap in /usr/local/lib/python3.12/dist-packages (0.59.0)
Requirement already satisfied: lonboard in /usr/local/lib/python3.12/dist-packages (0.13.0)
Requirement already satisfied: anywidget in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.9.21)
Requirement already satisfied: bqplot in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.12.45)
Requirement already satisfied: folium in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.20.0)
Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (from leafmap) (5.2.1)
Requirement already satisfied: geojson in /usr/local/lib/python3.12/dist-packages (from leafmap) (3.2.0)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (from leafmap) (1.1.2)
Requirement already satisfied: ipyevents in /usr/local/lib/python3.12/dist-packages (from leafmap) (2.0.4)
Requirement already satisfied: ipyfilechooser in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.6.0)
Requirement already satisfied: ipyleaflet in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.20.0)
Requirement already satisfied: ipyvuetify in /usr/local/lib/python3.12/dist-packages (from leafmap) (1.11.3)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/dist-packages (from leafmap) (7.7.1)
Requirement already satisfied: maplibre in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.3.6)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from leafmap) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from leafmap) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from leafmap) (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from leafmap) (5.24.1)
Requirement already satisfied: pystac-client in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.9.0)
Requirement already satisfied: python-box in /usr/local/lib/python3.12/dist-packages (from leafmap) (7.3.2)
Requirement already satisfied: scooby in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.11.0)
Requirement already satisfied: whiteboxgui in /usr/local/lib/python3.12/dist-packages (from leafmap) (2.3.0)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from leafmap) (2025.11.0)
Requirement already satisfied: arro3-compute>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from lonboard) (0.6.5)
Requirement already satisfied: arro3-core>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from lonboard) (0.6.5)
Requirement already satisfied: arro3-io>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from lonboard) (0.6.5)
Requirement already satisfied: geoarrow-rust-core>=0.5.2 in /usr/local/lib/python3.12/dist-packages (from lonboard) (0.6.1)
Requirement already satisfied: pyproj>=3.3 in /usr/local/lib/python3.12/dist-packages (from lonboard) (3.7.2)
Requirement already satisfied: traitlets>=5.7.1 in /usr/local/lib/python3.12/dist-packages (from lonboard) (5.7.1)
Requirement already satisfied: typing-extensions>=4.12.0 in /usr/local/lib/python3.12/dist-packages (from lonboard) (4.15.0)
Requirement already satisfied: psygnal>=0.8.1 in /usr/local/lib/python3.12/dist-packages (from anywidget->leafmap) (0.15.1)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (3.6.10)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (7.34.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (3.0.16)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyproj>=3.3->lonboard) (2026.1.4)
Requirement already satisfied: traittypes>=0.0.6 in /usr/local/lib/python3.12/dist-packages (from bqplot->leafmap) (0.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->leafmap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->leafmap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->leafmap) (2025.3)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium->leafmap) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium->leafmap) (3.1.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium->leafmap) (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown->leafmap) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown->leafmap) (3.20.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown->leafmap) (4.67.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas->leafmap) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas->leafmap) (26.0)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas->leafmap) (2.1.2)
Requirement already satisfied: jupyter-leaflet<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from ipyleaflet->leafmap) (0.20.0)
Requirement already satisfied: ipyvue<2,>=1.7 in /usr/local/lib/python3.12/dist-packages (from ipyvuetify->leafmap) (1.11.3)
Requirement already satisfied: eval-type-backport in /usr/local/lib/python3.12/dist-packages (from maplibre->leafmap) (0.3.1)
Requirement already satisfied: pydantic>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from maplibre->leafmap) (2.12.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->leafmap) (9.1.2)
Requirement already satisfied: pystac>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from pystac[validation]>=1.10.0->pystac-client->leafmap) (1.14.3)
Requirement already satisfied: ipytree in /usr/local/lib/python3.12/dist-packages (from whiteboxgui->leafmap) (0.2.2)
Requirement already satisfied: whitebox in /usr/local/lib/python3.12/dist-packages (from whiteboxgui->leafmap) (2.3.6)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (0.2.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (6.5.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (4.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium->leafmap) (3.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.3->maplibre->leafmap) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.3->maplibre->leafmap) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.3->maplibre->leafmap) (0.4.2)
Requirement already satisfied: jsonschema~=4.18 in /usr/local/lib/python3.12/dist-packages (from pystac[validation]>=1.10.0->pystac-client->leafmap) (4.26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->leafmap) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium->leafmap) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium->leafmap) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->folium->leafmap) (2.5.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->leafmap) (6.5.7)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown->leafmap) (2.8.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown->leafmap) (1.7.1)
Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.12/dist-packages (from whitebox->whiteboxgui->leafmap) (8.3.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets->leafmap) (0.8.5)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (0.30.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->leafmap) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->leafmap) (5.9.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (25.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (7.17.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.24.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.3.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets->leafmap) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets->leafmap) (0.5.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->leafmap) (4.5.1)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.2.4)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.21.2)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (25.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.4.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.14.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (3.0)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (4.12.1)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.5.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (7.7.0)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.9.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (4.0.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (6.0.3)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.1.1)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (20.11.0)

Download the [nyc_data.zip](https://github.com/opengeos/data/raw/main/duckdb/nyc_data.zip) dataset using leafmap. The zip file contains the following datasets. Create a new DuckDB database and import the datasets into the database. Each dataset should be imported into a separate table.

- nyc_census_blocks
- nyc_homicides
- nyc_neighborhoods
- nyc_streets
- nyc_subway_stations

In [3]:
url="https://github.com/opengeos/data/raw/main/duckdb/nyc_data.zip"
leafmap.download_file(url,unzip=True)

nyc_data.zip already exists. Skip downloading. Set overwrite=True to overwrite.

'/content/nyc_data.zip'

In [4]:
con=duckdb.connect()
con.install_extension('spatial')
con.load_extension('spatial')

In [5]:
# read census_blocks.shp
con.sql("""
CREATE TABLE IF NOT EXISTS cs AS
SELECT * FROM ST_Read('nyc_census_blocks.shp')
""")

In [6]:
con.table('cs')

┌─────────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬───────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│      BLKID      │ POPN_TOTAL │ POPN_WHITE │ POPN_BLACK │ POPN_NATIV │ POPN_ASIAN │ POPN_OTHER │   BORONAME    │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      geom                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      │
│     varchar     │   int64    │   int64    │   int64    │   int64    │   int64    │   int64    │    varchar    │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    geometry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    │
├─────────────────┼────────────┼────────────┼────────────┼────────────┼────────────┼────────────┼───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 360850009001000 │         97 │         51 │         32 │          1 │          5 │          8 │ Staten Island │ POLYGON ((577856.5470479821 4499583.234929237, 577862.6350194028 4499572.986942291, 577797.7431656285 4499531.836501671, 577738.664796277 4499627.642337196, 577720.2023628965 4499657.818370118, 577624.4382330556 4499647.118713528, 577613.2357513051 4499666.932090907, 577587.4900580458 4499715.230511688, 577763.9666999553 4499733.519348773, 577856.5470479821 4499583.234929237))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    │
│ 360850020011000 │         66 │         52 │          2 │          0 │          7 │          5 │ Staten Island │ POLYGON ((578620.7173632095 4495974.817866362, 578535.3576332723 4495915.809992479, 578524.626146389 4495908.449928109, 578475.1516588356 4495981.940162353, 578550.5382256601 4496033.2756218575, 578571.6880872999 4496047.752238923, 578620.7173632095 4495974.817866362))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  │
│ 360850040001000 │         62 │         14 │         18 │          2 │         25 │          3 │ Staten Island │ POLYGON ((577227.2244709881 4495995.066845497, 577155.6250310685 4495899.946972164, 577077.1787859342 4495959.14840101, 577121.3799610958 4496049.833796346, 577131.0046544907 4496068.630318046, 577227.2244709881 4495995.066845497))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        │
│ 360850074001000 │        137 │         92 │         12 │          0 │         13 │         20 │ Staten Island │ POLYGON ((579037.0332016965 4494421.769816227, 579000.0152762784 4494400.8946105875, 578976.4815953767 4494387.765575125, 578908.801775808 4494521.2091746535, 578974.2487792528 4494550.841294147, 579004.0863603267 4494563.909898213, 579014.1554114621 4494528.832636419, 579023.0136663909 4494493.408570291, 579030.6435324465 4494457.699749923, 579037.0332016965 4494421.769816227))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  │
│ 360850096011000 │        289 │        230 │          0 │          0 │         32 │         27 │ Staten Island │ POLYGON ((577652.4825280879 4494975.052285533, 577681.9143370368 4494930.307676212, 577720.5586226447 4494862.963829213, 577727.3289497155 4494849.754381681, 577732.581515847 4494835.767709447, 577736.1983562167 4494821.271668449, 577738.1241678909 4494806.553481156, 577741.0522650707 4494783.424021987, 577619.6171554218 4494726.97852215, 577587.3559694993 4494795.137760404, 577440.4890988736 4494723.787243782, 577407.4433355835 4494794.037897717, 577398.6917565296 4494812.944467689, 577450.8955504326 4494959.7947593825, 577471.4243214849 4494965.581638442, 577506.8288100478 4494890.028127626, 577536.1900156969 4494904.272123218, 577512.836425658 4494971.905691302, 577599.3220771316 4494978.181154193, 577652.4825280879 4494975.052285533))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   │
│ 360850112011000 │         83 │         63 │          0 │          0 │         18 │          2 │ Staten Island │ POLYGON ((577305.0606213677 4492950.1205372885, 577301.2972957928 4492944.603255557, 577281.6853667679 4492915.846983125, 577260.9972937243 4492873.659282748, 577086.2399955298 4492993.263227337, 577133.0934718297 4493058.110367223, 577138.4349902926 4493065.504115443, 577305.0606213677 4492950.1205372885))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           │
│ 360850128041000 │        180 │        103 │         33 │          0 │         23 │         21 │ Staten Island │ POLYGON ((575441.898302898 4491397.132737916, 575623.9684967292 4491272.617317605, 575540.8448091304 4491131.384355877, 575535.7561513839 4491122.761859279, 575502.5112266715 4491066.430530817, 575433.4751126925 4490949.449963717, 575329.7375088218 4490773.670344726, 575161.3837069425 4490904.621920971, 575025.9797051002 4491009.186919867, 575020.6655067619 4491013.290344792, 575071.3829727351 4491079.449512988, 575116.6532516159 4491139.769390702, 575165.0916763709 4491205.365870911, 575211.0681381105 4491266.7994918525, 575260.891091985 4491332.582663486, 575308.9395565627 4491395.632414687, 575354.8603762029 4491457.4753504945, 575360.0035038401 4491453.909765155, 575441.898302898 4491397.132737916))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       │
│ 360850138001000 │         22 │         22 │          0 │          0 │          0 │          0 │ Staten Island │ POLYGON ((573055.2945856147 4491621.860057309, 572936.5777776275 4491601.766410038, 572922.6229879115 4491685.504718478, 572950.2781064857 4491690.188677361, 573042.9206625067 4491705.395378966, 573055.2945856147 4491621.860057309))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       │

In [7]:
# read nyc_homicides.shp
con.sql("""
CREATE TABLE IF NOT EXISTS h AS
SELECT * FROM ST_Read('nyc_homicides.shp')
""")
con.table('h')

┌────────────┬───────────────┬────────────┬────────────┬───────┬─────────┬────────────┬───────┬──────────────────────────────────────────────┐
│ INCIDENT_D │   BORONAME    │ NUM_VICTIM │ PRIMARY_MO │  ID   │ WEAPON  │ LIGHT_DARK │ YEAR  │                     geom                     │
│    date    │    varchar    │  varchar   │  varchar   │ int64 │ varchar │  varchar   │ int64 │                   geometry                   │
├────────────┼───────────────┼────────────┼────────────┼───────┼─────────┼────────────┼───────┼──────────────────────────────────────────────┤
│ 2008-01-01 │ Brooklyn      │ 1          │ NULL       │     7 │ gun     │ D          │  2008 │ POINT (592158.6657641566 4502210.892367315)  │
│ 2008-01-04 │ Manhattan     │ 1          │ NULL       │    14 │ gun     │ D          │  2008 │ POINT (588654.9516122746 4517855.382656676)  │
│ 2008-01-05 │ Queens        │ 1          │ NULL       │    15 │ gun     │ D          │  2008 │ POINT (605800.8150245796 4505730.608395767)  │
│ 2008-01-04 │ Queens        │ 1          │ NULL       │    16 │ knife   │ D          │  2008 │ POINT (594255.1571757384 4512250.378115875)  │
│ 2008-01-05 │ Queens        │ 1          │ NULL       │    18 │ gun     │ D          │  2008 │ POINT (605498.1350349792 4496052.6404242935) │
│ 2008-01-07 │ Brooklyn      │ 1          │ NULL       │    20 │ gun     │ D          │  2008 │ POINT (592020.9986062422 4505733.647394002)  │
│ 2008-01-10 │ Manhattan     │ 1          │ NULL       │    22 │ gun     │ D          │  2008 │ POINT (584055.5176806634 4511774.7240870865) │
│ 2008-01-10 │ Manhattan     │ 1          │ NULL       │    23 │ gun     │ D          │  2008 │ POINT (587283.7480292964 4516908.389954502)  │
│ 2008-01-13 │ Staten Island │ 1          │ NULL       │    25 │ gun     │ D          │  2008 │ POINT (570593.1246245154 4498222.780018244)  │
│ 2008-01-16 │ Queens        │ 1          │ NULL       │    27 │ gun     │ D          │  2008 │ POINT (607385.9693839889 4501506.717170785)  │
│     ·      │   ·           │ ·          │  ·         │     · │  ·      │ ·          │    ·  │                      ·                       │
│     ·      │   ·           │ ·          │  ·         │     · │  ·      │ ·          │    ·  │                      ·                       │
│     ·      │   ·           │ ·          │  ·         │     · │  ·      │ ·          │    ·  │                      ·                       │
│ 2010-10-26 │ The Bronx     │ 1          │ NULL       │  4252 │ knife   │ NULL       │  2010 │ POINT (592570.4068967762 4518519.960392341)  │
│ 2010-10-24 │ The Bronx     │ 1          │ NULL       │  4253 │ NULL    │ NULL       │  2010 │ POINT (592289.2525188073 4520907.942087955)  │
│ 2010-10-23 │ The Bronx     │ 1          │ NULL       │  4258 │ gun     │ NULL       │  2010 │ POINT (595691.929813581 4525486.773996004)   │
│ 2010-07-05 │ The Bronx     │ 1          │ NULL       │  4260 │ NULL    │ NULL       │  2011 │ POINT (591908.9889569259 4520517.284502078)  │
│ 2010-10-17 │ The Bronx     │ 1          │ NULL       │  4263 │ knife   │ NULL       │  2010 │ POINT (591526.0795441027 4518120.5985546755) │
│ 2010-10-11 │ The Bronx     │ 1          │ NULL       │  4269 │ gun     │ NULL       │  2010 │ POINT (592515.9578506276 4523492.764356317)  │
│ 2010-10-06 │ The Bronx     │ 1          │ NULL       │  4271 │ knife   │ NULL       │  2010 │ POINT (594347.5429990037 4522235.809302402)  │
│ 2011-07-26 │ The Bronx     │ 1          │ NULL       │  4282 │ gun     │ NULL       │  2011 │ POINT (592849.08922107 4522545.555276063)    │
│ 2011-07-28 │ The Bronx     │ 1          │ NULL       │  4284 │ gun     │ NULL       │  2011 │ POINT (596872.5868381617 4528682.876480885)  │
│ 2011-08-01 │ The Bronx     │ 1          │ NULL       │  4291 │ gun     │ NULL       │  2011 │ POINT (591083.4961042595 4519237.413713751)  │
├────────────┴───────────────┴────────────┴────────────┴───────┴─────────┴────────────┴───────┴──────────────────────────────────────────────┤
│ 3982 rows (20 shown)                                                                                                             9 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [8]:
# read nyc_neighborhoods.shp
con.sql("""
CREATE TABLE IF NOT EXISTS n AS
SELECT * FROM ST_Read('nyc_neighborhoods.shp')
""")
con.table('n')

┌───────────────┬──────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐

In [9]:
# read nyc_streets.shp
con.sql("""
CREATE TABLE IF NOT EXISTS s AS
SELECT * FROM ST_Read('nyc_streets.shp')
""")
con.table('s')

┌───────┬─────────────────┬─────────┬───────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  ID   │      NAME       │ ONEWAY  │     TYPE      │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    geom                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     │
│ int64 │     varchar     │ varchar │    varchar    │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  geometry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   │
├───────┼─────────────────┼─────────┼───────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     1 │ Shore Pky S     │ NULL    │ residential   │ LINESTRING (586785.4767897038 4492901.0014554765, 586898.2320050898 4492943.72547124, 587118.9878110565 4493001.146262758, 587234.7882154312 4493037.249899771, 587431.3615337512 4493019.236842211, 587561.2768490226 4493012.990702256)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   │
│     2 │ NULL            │ NULL    │ footway       │ LINESTRING (586645.0073625665 4504977.750360583, 586664.2248992481 4504988.543891153, 586672.1505418627 4504992.977345291, 586681.4789395962 4505001.757018659, 586688.6359095252 4505009.778609065, 586694.2634942597 4505025.020941579, 586697.0013043515 4505038.786255697, 586696.5672141062 4505041.223656929, 586694.6695629463 4505051.759630491, 586688.7973123307 4505058.196914113, 586680.7704003028 4505062.444128611, 586668.4258816248 4505063.743290105, 586659.7820877017 4505058.579815893, 586650.403081951 4505054.14051223)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             │
│     3 │ Avenue O        │ NULL    │ residential   │ LINESTRING (586750.3019977848 4496109.72213903, 586837.37268806 4496123.393417588, 586929.0880637383 4496137.786070599, 587015.1469008185 4496151.114572097, 587093.4343798014 4496163.353985042, 587171.7190240856 4496175.816234934, 587287.5857396824 4496194.048793765, 587403.3713812231 4496211.938057109, 587494.0707974355 4496226.225884001, 587572.3555287877 4496238.581363495, 587650.7259237112 4496250.827661535, 587734.5750873999 4496264.804656505, 587819.2869244645 4496277.349516686, 587898.3320165256 4496289.717422236, 587975.7774558993 4496301.401149125, 588053.8915465927 4496313.759718864, 588085.0540988253 4496318.569170746, 588132.3464027026 4496325.90110842, 588213.7623648852 4496338.744539772, 588294.9073716206 4496351.585655665, 588374.458581502 4496363.964662071, 588480.8633188349 4496380.604860281, 588563.37009399 4496393.409601895, 588641.578106669 4496405.553467086, 588719.6831848478 4496417.796852784, 588798.2205097184 4496429.957404145, 588879.202961951 4496442.803004715, 588960.3569963054 4496455.4295026995, 589035.3067186901 4496463.31981405)                                                                                                                                                                                                                                                                                                                                                                                                                         │
│     4 │ Walsh Ct        │ NULL    │ residential   │ LINESTRING (586728.695515043 4497971.05313857, 586886.3582256545 4498000.5364795)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           │
│     5 │ NULL            │ NULL    │ motorway_link │ LINESTRING (586587.0531467082 4510088.250402982, 586641.7339853322 4510156.834975086)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       │
│     6 │ Avenue Z        │ NULL    │ residential   │ LINESTRING (586792.1590947693 4493279.321965924, 586978.5335762373 4493308.472654313, 587056.7691259042 4493320.488157582, 587135.2544337203 4493332.840467822, 587213.4856216063 4493345.190637635, 587291.4600901009 4493357.760667622, 587370.1087308106 4493370.561464139, 587489.9990153251 4493388.621033584, 587683.4666829993 4493418.76094142, 587758.7408266276 4493430.526991442, 587836.7995705899 4493442.992749805, 587979.9986997165 4493465.220749474, 588064.7428141944 4493478.433970737, 588162.0566480169 4493493.684207905, 588252.3677999103 4493507.742587921, 588331.1906263772 4493519.889559386, 588377.8262378025 4493526.992708679, 588409.5914086028 4493531.921344224, 588487.6468680383 4493544.504960426, 588520.4247695546 4493549.668139077, 588565.7073635312 4493556.645380988, 588647.0627205392 4493569.269903921, 588728.2472545553 4493582.00430875, 588808.8418079352 4493594.510533638, 588914.7789989482 4493611.050281803, 588996.8917129147 4493623.954142952, 589075.6334952639 4493636.330129092, 589153.5171845561 4493648.252606061, 589231.65633504 4493660.734065213, 589313.0915890371 4493673.588920103, 589394.2741799683 4493686.319518985, 589472.7562905363 4493698.374663421, 589550.981764403 4493710.638496167, 589628.615974486 4493722.785024423, 589716.3860416674 4493736.608693888, 589797.3979978329 4493749.35277061, 589875.7111361583 4493761.28803672, 589953.8521202526 4493773.444095962, 590031.9109318687 4493785.377947366, 590113.8514201366 4493798.247735203) │
│     7 │ Dank Ct         │ NULL    │ residential   │ LINESTRING (586794.7541421958 4493361.728529104, 586966.095369606 4493387.928398192)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        │
│     8 │ Cumberland Walk │ NULL    │ footway       │ LINESTRING (586657.467661773 4505324.904212245, 586692.489041438 4505320.983270284, 586707.7622544948 4505272.201195538, 586724.924106783 4505213.671328205)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │

In [10]:
# read nyc_subway_stations.shp
con.sql("""
CREATE TABLE IF NOT EXISTS ss AS
SELECT * FROM ST_Read('nyc_subway_stations.shp')
""")
con.table('ss')

┌──────────┬────────┬───────────────────┬─────────────────┬─────────────────┬─────────────────────────────────────────┬───────────────────────────────────┬───────────┬─────────┬─────────┬───────────┬──────────────┬─────────┬─────────┬──────────────────────────────────────────────┐
│ OBJECTID │   ID   │       NAME        │    ALT_NAME     │    CROSS_ST     │                LONG_NAME                │               LABEL               │  BOROUGH  │ NGHBHD  │ ROUTES  │ TRANSFERS │    COLOR     │ EXPRESS │ CLOSED  │                     geom                     │
│  double  │ double │      varchar      │     varchar     │     varchar     │                 varchar                 │              varchar              │  varchar  │ varchar │ varchar │  varchar  │   varchar    │ varchar │ varchar │                   geometry                   │
├──────────┼────────┼───────────────────┼─────────────────┼─────────────────┼─────────────────────────────────────────┼───────────────────────────────────┼───────────┼─────────┼─────────┼───────────┼──────────────┼─────────┼─────────┼──────────────────────────────────────────────┤
│      1.0 │  376.0 │ Cortlandt St      │ NULL            │ Church St       │ Cortlandt St (R,W) Manhattan            │ Cortlandt St (R,W)                │ Manhattan │ NULL    │ R,W     │ R,W       │ YELLOW       │ NULL    │ NULL    │ POINT (583521.854408956 4507077.862599085)   │
│      2.0 │    2.0 │ Rector St         │ NULL            │ NULL            │ Rector St (1) Manhattan                 │ Rector St (1)                     │ Manhattan │ NULL    │ 1       │ 1         │ RED          │ NULL    │ NULL    │ POINT (583324.4866324601 4506805.373160211)  │
│      3.0 │    1.0 │ South Ferry       │ NULL            │ NULL            │ South Ferry (1) Manhattan               │ South Ferry (1)                   │ Manhattan │ NULL    │ 1       │ 1         │ RED          │ NULL    │ NULL    │ POINT (583304.1823994748 4506069.654048115)  │
│      4.0 │  125.0 │ 138th St          │ Grand Concourse │ Grand Concourse │ 138th St / Grand Concourse (4,5) Bronx  │ 138th St / Grand Concourse (4,5)  │ Bronx     │ NULL    │ 4,5     │ 4,5       │ GREEN        │ NULL    │ NULL    │ POINT (590250.10594797 4518558.019924332)    │
│      5.0 │  126.0 │ 149th St          │ Grand Concourse │ Grand Concourse │ 149th St / Grand Concourse (4) Bronx    │ 149th St / Grand Concourse (4)    │ Bronx     │ NULL    │ 4       │ 2,4,5     │ GREEN        │ express │ NULL    │ POINT (590454.7399891173 4519145.719617855)  │
│      6.0 │   45.0 │ 149th St          │ Grand Concourse │ Grand Concourse │ 149th St / Grand Concourse (2,5) Bronx  │ 149th St / Grand Concourse (2,5)  │ Bronx     │ NULL    │ 2,5     │ 2,4,5     │ RED-GREEN    │ express │ NULL    │ POINT (590465.8934191109 4519168.697483203)  │
│      7.0 │  127.0 │ 161st St          │ Yankee Stadium  │ River Ave       │ 161st St / Yankee Stadium (B,D,4) Bronx │ 161st St / Yankee Stadium (B,D,4) │ Bronx     │ NULL    │ B,D,4   │ B,D,4     │ GREEN-ORANGE │ NULL    │ NULL    │ POINT (590573.169495527 4520214.766177284)   │
│      8.0 │  208.0 │ 167th St          │ NULL            │ Grand Concourse │ 167th St (B,D) Bronx                    │ 167th St (B,D)                    │ Bronx     │ NULL    │ B,D     │ B,D       │ ORANGE       │ NULL    │ NULL    │ POINT (591252.8314104103 4520950.353355553)  │
│      9.0 │  128.0 │ 167th St          │ NULL            │ River Ave       │ 167th St (4) Bronx                      │ 167th St (4)                      │ Bronx     │ NULL    │ 4       │ 4         │ GREEN        │ NULL    │ NULL    │ POINT (590946.3972262995 4521077.318976877)  │
│     10.0 │  209.0 │ 170th St          │ NULL            │ Grand Concourse │ 170th St (B,D) Bronx                    │ 170th St (B,D)                    │ Bronx     │ NULL    │ B,D     │ B,D       │ ORANGE       │ NULL    │ NULL    │ POINT (591583.6111452815 4521434.846626811)  │
│       ·  │    ·   │    ·              │  ·              │  ·              │          ·                              │       ·                           │   ·       │  ·      │  ·      │  ·        │   ·          │  ·      │  ·      │                      ·                       │
│       ·  │    ·   │    ·              │  ·              │  ·              │          ·                              │       ·                           │   ·       │  ·      │  ·      │  ·        │   ·          │  ·      │  ·      │                      ·                       │
│       ·  │    ·   │    ·              │  ·              │  ·              │          ·                              │       ·                           │   ·       │  ·      │  ·      │  ·        │   ·          │  ·      │  ·      │                      ·                       │
│    482.0 │  904.0 │ JFK Terminal 1    │ NULL            │ NULL            │ JFK Terminal 1, Queens                  │ JFK Terminal 1                    │ Queens    │ NULL    │ NULL    │ NULL      │ AIR-BLUE     │ NULL    │ NULL    │ POINT (602356.9561669775 4499829.669655836)  │
│    483.0 │  905.0 │ JFK Terminal 2-3  │ NULL            │ NULL            │ JFK Terminal 2-3, Queens                │ JFK Terminal 2-3                  │ Queens    │ NULL    │ NULL    │ NULL      │ AIR-BLUE     │ NULL    │ NULL    │ POINT (602526.112504933 4499699.646828213)   │
│    484.0 │  906.0 │ JFK Terminal 4    │ NULL            │ NULL            │ JFK Terminal 4, Queens                  │ JFK Terminal 4                    │ Queens    │ NULL    │ NULL    │ NULL      │ AIR-BLUE     │ NULL    │ NULL    │ POINT (602985.6731458901 4499897.286220534)  │
│    485.0 │  907.0 │ JFK Terminal 5-6  │ NULL            │ NULL            │ JFK Terminal 5-6, Queens                │ JFK Terminal 5-6                  │ Queens    │ NULL    │ NULL    │ NULL      │ AIR-BLUE     │ NULL    │ NULL    │ POINT (603245.7503829238 4500232.851042057)  │
│    486.0 │  908.0 │ JFK Terminal 7    │ NULL            │ NULL            │ JFK Terminal 7, Queens                  │ JFK Terminal 7                    │ Queens    │ NULL    │ NULL    │ NULL      │ AIR-BLUE     │ NULL    │ NULL    │ POINT (602880.326628096 4500459.602709553)   │
│    487.0 │  909.0 │ JFK Terminal 8    │ NULL            │ NULL            │ JFK Terminal 8, Queens                  │ JFK Terminal 8                    │ Queens    │ NULL    │ NULL    │ NULL      │ AIR-BLUE     │ NULL    │ NULL    │ POINT (602433.3533596311 4500363.8128236225) │
│    488.0 │  903.0 │ Federal Circle    │ Rental Car      │ NULL            │ Federal Circle / Rental Car, Queens     │ Federal Circle / Rental Car       │ Queens    │ NULL    │ NULL    │ NULL      │ AIR-BLUE     │ NULL    │ NULL    │ POINT (600903.1428474564 4501689.113908147)  │
│    489.0 │  902.0 │ Long Term Parking │ NULL            │ NULL            │ Long Term Parking, Queens               │ Long Term Parking                 │ Queens    │ NULL    │ NULL    │ NULL      │ AIR-BLUE     │ NULL    │ NULL    │ POINT (599552.1129832724 4502056.229470152)  │
│    490.0 │  901.0 │ Howard Beach      │ NULL            │ 159th Ave       │ Howard Beach, Queens                    │ Howard Beach                      │ Queens    │ NULL    │ NULL    │ A         │ AIR-BLUE     │ NULL    │ NULL    │ POINT (598862.0205107569 4501868.071868393)  │
│    491.0 │  900.0 │ Jamaica           │ Sutphin Blvd    │ Sutphin Blvd    │ Jamaica / Sutphin Blvd, Queens          │ Jamaica / Sutphin Blvd            │ Queens    │ NULL    │ NULL    │ E,J,Z     │ AIR-BLUE     │ NULL    │ NULL    │ POINT (600689.9370847167 4506179.234498333)  │
├──────────┴────────┴───────────────────┴─────────────────┴─────────────────┴─────────────────────────────────────────┴───────────────────────────────────┴───────────┴─────────┴─────────┴───────────┴──────────────┴─────────┴─────────┴──────────────────────────────────────────────┤
│ 491 rows (20 shown)                                                                                                                                                                                                                                                        15 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [11]:
con.sql("SHOW TABLES")

┌─────────┐
│  name   │
│ varchar │
├─────────┤
│ cs      │
│ h       │
│ n       │
│ s       │
│ ss      │
└─────────┘

1. **What subway station is in \'Little Italy\'? What subway route is it on?**

In [12]:
con.sql("""
SELECT ss.name, ss.routes
FROM ss
JOIN n
ON ST_Intersects(ss.geom, n.geom)
WHERE n.name = 'Little Italy';
""")

┌───────────┬─────────┐
│   NAME    │ ROUTES  │
│  varchar  │ varchar │
├───────────┼─────────┤
│ Spring St │ 6       │
└───────────┴─────────┘

2. **What are all the neighborhoods served by the 6-train?** (Hint: The `routes` column in the `nyc_subway_stations` table has values like \'B,D,6,V\' and \'C,6\')

In [13]:
con.sql("""
SELECT DISTINCT n.name, n.boroname
FROM n
JOIN ss
ON ST_Intersects(n.geom, ss.geom)
WHERE strpos(ss.routes,'6')>0;
""")

┌────────────────────┬───────────┐
│        NAME        │ BORONAME  │
│      varchar       │  varchar  │
├────────────────────┼───────────┤
│ Midtown            │ Manhattan │
│ Upper East Side    │ Manhattan │
│ Hunts Point        │ The Bronx │
│ East Harlem        │ Manhattan │
│ South Bronx        │ The Bronx │
│ Yorkville          │ Manhattan │
│ Gramercy           │ Manhattan │
│ Mott Haven         │ The Bronx │
│ Murray Hill        │ Manhattan │
│ Soundview          │ The Bronx │
│ Greenwich Village  │ Manhattan │
│ Financial District │ Manhattan │
│ Parkchester        │ The Bronx │
│ Little Italy       │ Manhattan │
│ Chinatown          │ Manhattan │
├────────────────────┴───────────┤
│ 15 rows              2 columns │
└────────────────────────────────┘

3. **After 9/11, the \'Battery Park\' neighborhood was off limits for several days. How many people had to be evacuated?**

In [14]:
con.sql("""
SELECT SUM(popn_total)
FROM cs
JOIN n
ON ST_Intersects(n.geom, cs.geom)
WHERE n.name = 'Battery Park'
""")

┌─────────────────┐
│ sum(popn_total) │
│     int128      │
├─────────────────┤
│           17153 │
└─────────────────┘

4. **What neighborhood has the highest population density (persons/km2)?**

In [15]:
con.sql("""
SELECT n.name, SUM(cs.popn_total)/(ST_Area(n.geom)/1000000) AS density
FROM n
JOIN cs
ON ST_Intersects(n.geom, cs.geom)
GROUP BY n.name, n.geom
ORDER BY density DESC
LIMIT 1
""")

┌───────────────────┬───────────────────┐
│       NAME        │      density      │
│      varchar      │      double       │
├───────────────────┼───────────────────┤
│ North Sutton Area │ 68435.13283772678 │
└───────────────────┴───────────────────┘

When you're finished, you can check your answers [here](https://postgis.net/workshops/postgis-intro/joins_exercises.html).

# Ship-to-Ship Transfer Detection

Now for a less structured exercise. We're going to look at ship-to-ship transfers. The idea is that two ships meet up in the middle of the ocean, and one ship transfers cargo to the other. This is a common way to avoid sanctions, and is often used to transfer oil from sanctioned countries to other countries. We're going to look at a few different ways to detect these transfers using AIS data.

In [16]:
%pip install duckdb duckdb-engine jupysql

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.4.4)
Requirement already satisfied: duckdb-engine in /usr/local/lib/python3.12/dist-packages (0.17.0)
Requirement already satisfied: jupysql in /usr/local/lib/python3.12/dist-packages (0.11.1)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.12/dist-packages (from duckdb-engine) (26.0)
Requirement already satisfied: sqlalchemy>=1.3.22 in /usr/local/lib/python3.12/dist-packages (from duckdb-engine) (2.0.46)
Requirement already satisfied: prettytable>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from jupysql) (3.17.0)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.12/dist-packages (from jupysql) (0.5.5)
Requirement already satisfied: ipython-genutils>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from jupysql) (3.1.6)
Requirement already satisfied: sqlglot>=11.3.7 in /usr/local/lib/python3.12/dist-packages (from jupysql) (25.20.2)
Requirement already satisfied: jupysql-plugin>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from jupysql) (0.4.5)
Requirement already satisfied: ploomber-core>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from jupysql) (0.2.27)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from ploomber-core>=0.2.7->jupysql) (6.0.3)
Requirement already satisfied: posthog>=3.0 in /usr/local/lib/python3.12/dist-packages (from ploomber-core>=0.2.7->jupysql) (7.8.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.12.0->jupysql) (0.5.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.3.22->duckdb-engine) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.3.22->duckdb-engine) (4.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->jupysql) (3.0.3)
Requirement already satisfied: requests<3.0,>=2.7 in /usr/local/lib/python3.12/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.32.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.17.0)
Requirement already satisfied: python-dateutil>=2.2 in /usr/local/lib/python3.12/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.9.0.post0)
Requirement already satisfied: backoff>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2026.1.4)

In [17]:
import duckdb
import pandas as pd

# Import jupysql Jupyter extension to create SQL cells
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False
%sql duckdb:///:memory:

In [18]:
%%sql
INSTALL httpfs;
LOAD httpfs;
INSTALL spatial;
LOAD spatial;

Empty DataFrame
Columns: [Success]
Index: []

## Step 1

Create a spatial database using the following AIS data:

https://storage.googleapis.com/qm2/casa0025_ships.csv

Each row in this dataset is an AIS 'ping' indicating the position of a ship at a particular date/time, alongside vessel-level characteristics.

It contains the following columns:
* `vesselid`: A unique numerical identifier for each ship, like a license plate
* `vessel_name`: The ship's name
* `vsl_descr`: The ship's type
* `dwt`: The ship's Deadweight Tonnage (how many tons it can carry)
* `v_length`: The ship's length in meters
* `draught`: How many meters deep the ship is draughting (how low it sits in the water). Effectively indicates how much cargo the ship is carrying
* `sog`: Speed over Ground (in knots)
* `date`: A timestamp for the AIS signal
* `lat`: The latitude of the AIS signal (EPSG:4326)
* `lon`: The longitude of the AIS signal (EPSG:4326)

Create a table called 'ais' where each row is a different AIS ping, with no superfluous information. Construct a geometry column.

Create a second table called 'vinfo' which contains vessel-level information with no superfluous information.

You can set a spatial index on each of these tables as follows:

`CREATE INDEX index_name ON table_name USING RTREE(geom);`

In [19]:
%%sql
CREATE OR REPLACE TABLE ais AS
SELECT DISTINCT vesselid, date, sog, draught, ST_Point(lon,lat) AS geom
FROM 'https://storage.googleapis.com/qm2/casa0025_ships.csv';
FROM ais

,vesselid,date,sog,draught,geom
0,350053,2022-07-25 02:53:29,5.2,3.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
1,350053,2022-07-25 03:09:37,0.7,3.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
2,350053,2022-07-25 04:16:06,0.1,3.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
3,350053,2022-07-25 05:20:17,0.0,3.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
4,350053,2022-07-25 07:25:25,0.0,3.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
...,...,...,...,...,...
101252,217531,2022-08-10 12:13:45,0.0,4.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
101253,217531,2022-08-10 13:13:51,0.1,4.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
101254,217531,2022-08-10 14:16:47,0.1,4.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
101255,217531,2022-08-23 06:06:51,8.3,4.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
101256,217531,2022-08-23 06:14:23,9.5,4.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."

In [20]:
%%sql
CREATE TABLE IF NOT EXISTS vinfo AS
SELECT DISTINCT
vesselid,
vessel_name,
vsl_descr,
dwt,
v_length
FROM 'https://storage.googleapis.com/qm2/casa0025_ships.csv';
FROM vinfo;

,vesselid,vessel_name,vsl_descr,dwt,v_length
0,323648,A Line,bulk carrier,12259.0,109.0
1,285151,Adler,roll on roll off with container capacity,7331.0,120.0
2,142145,Agnes,general cargo,3637.0,107.0
3,255056,Ahmet Telli,chemical tanker,6025.0,104.0
4,270983,Aksay,general cargo,3541.0,108.0
...,...,...,...,...,...
830,327047,Zernograd,general cargo with container capacity,6207.0,140.0
831,272505,Zhadeit,general cargo,3775.0,139.0
832,10528606,Zhibek Zholy,general cargo,7146.0,140.0
833,356770,Zoi XL,bulk carrier,82489.0,229.0
834,217531,Zubeyde,roll on roll off with container capacity,5000.0,113.0

## Step 2

Use a spatial join to identify ship-to-ship transfers in this dataset.
Two ships are considered to be conducting a ship to ship transfer IF:

* They are within 500 meters of each other
* For more than two hours
* And their speed is lower than 1 knot

Some things to consider: make sure you're not joining ships with themselves. Try working with subsets of the data first while you try different things out.

In [24]:
%%sql
SELECT
a1.vesselid AS ship1,
a2.vesselid AS ship2,
a1.date AS start,
a2.date AS end
FROM ais AS a1
JOIN ais AS a2
ON ST_DWITHIN(a1.geom,a2.geom,500)
AND ABS(EXTRACT(EPOCH FROM (a2.date - a1.date))) >7200
AND a1.vesselid <> a2.vesselid
WHERE a1.sog <1 AND a2.sog<1
LIMIT 100;

     ship1   ship2               start                 end
0   323648  350053 2022-06-28 15:24:19 2022-07-25 03:09:37
1   323648  350053 2022-06-28 19:06:25 2022-07-25 03:09:37
2   323648  350053 2022-06-28 20:12:20 2022-07-25 03:09:37
3   323648  350053 2022-06-28 22:18:22 2022-07-25 03:09:37
4   323648  350053 2022-06-29 00:33:30 2022-07-25 03:09:37
..     ...     ...                 ...                 ...
95  213151  350053 2022-08-21 20:44:41 2022-07-25 03:09:37
96  213151  350053 2022-08-21 21:38:04 2022-07-25 03:09:37
97  213151  350053 2022-08-21 22:50:04 2022-07-25 03:09:37
98  213151  350053 2022-08-21 23:56:04 2022-07-25 03:09:37
99  213151  350053 2022-08-22 02:14:42 2022-07-25 03:09:37

[100 rows x 4 columns]

In [26]:
# Gemini给的更改
%%sql
SELECT
    a1.vesselid AS ship1,
    a2.vesselid AS ship2,
    MIN(a1.date) AS start_time,
    MAX(a1.date) AS end_time,
    (EXTRACT(EPOCH FROM MAX(a1.date) - MIN(a1.date)) / 3600) AS duration_hours
FROM ais AS a1
JOIN ais AS a2
    ON ST_DWithin(a1.geom, a2.geom, 500) -- 空间：距离小于500米
    AND ABS(EXTRACT(EPOCH FROM (a1.date - a2.date))) < 300 -- 时间：两艘船必须在同一时间出现（容差5分钟/300秒）
    AND a1.vesselid < a2.vesselid -- 技巧：用 < 既避免了自连接，也避免了 (A,B) 和 (B,A) 重复出现
WHERE a1.sog < 1
  AND a2.sog < 1
GROUP BY a1.vesselid, a2.vesselid -- 按“这一对船”分组
HAVING (MAX(a1.date) - MIN(a1.date)) > INTERVAL '2 hours' -- 筛选：持续时间超过2小时
LIMIT 100;

RuntimeError: (_duckdb.TransactionException) TransactionContext Error: Current transaction is aborted (please ROLLBACK)
[SQL: SELECT
    a1.vesselid AS ship1,
    a2.vesselid AS ship2,
    MIN(a1.date) AS start_time,
    MAX(a1.date) AS end_time,
    (EXTRACT(EPOCH FROM MAX(a1.date) - MIN(a1.date)) / 3600) AS duration_hours
FROM ais AS a1
JOIN ais AS a2
    ON ST_DWithin(a1.geom, a2.geom, 500)
    AND ABS(EXTRACT(EPOCH FROM (a1.date - a2.date))) < 300
    AND a1.vesselid < a2.vesselid
WHERE a1.sog < 1
  AND a2.sog < 1
GROUP BY a1.vesselid, a2.vesselid
HAVING (MAX(a1.date) - MIN(a1.date)) > INTERVAL '2 hours'
LIMIT 100;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)